
version: "3.7"
services:
  requirements:
    container_name: pygrn_catchup_requirements
    build:
      context: .
      dockerfile: docker/django/Dockerfile
      args:
        - EXTRA_REQUIREMENTS=devel
    image: pygrn_catchup_requirements
    entrypoint:
      - /bin/bash
    command: []

  db:
    container_name: pygrn_catchup_db
    build:
      context: docker/db/
      dockerfile: Dockerfile
    image: pygrn_catchup_db
    env_file:
     - app.env
    command: ["/bin/bash", "/app/docker/db/postgresql10.sh"]
    volumes:
      - .:/app
      - dbdata:/var/lib/postgresql/

  django:
    container_name: pygrn_catchup_django
    depends_on:
      - db
    image: pygrn_catchup_requirements
    env_file:
     - app.env
    command: ["/bin/bash", "/app/docker/wait-for-it.sh", "db:5432", "--", "/bin/bash", "/app/docker/django/runserver.sh"]
    volumes:
      - .:/app:cached
    ports:
      - 8000:8000
    networks:
      default:
        aliases:
          - catchup

volumes:
  dbdata:

networks:
  default:
    # external:
    #   name: pygrn
